version: '3.8'

services:
  web:
    build:
      context: .
    container_name: turismo_web
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DB_USUARIOS=pruebapython
      - MYSQL_DB_RESERVAS=reservas
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    container_name: turismo_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  db:
    image: mysql:8.0
    container_name: turismo_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
